image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.1208@sha256:f204d9bb8ad263d78e1a18e6f5220801fe0007a25412eccd03292f6cf7a56ed7

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    protocol: HTTP
    ports:
      main:
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

persistence:
  config:
    enabled: true
    mountPath: "/config"
