image:
  repository: tccr.io/truecharts/website-shot
  tag: latest@sha256:6e6e63fc0a5c4305e598cb993be3840df0ca6c3cdc54323c305467192122a5ff
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10221
        targetPort: 3000

persistence:
  screenshots:
    enabled: true
    mountPath: "/usr/src/website-shot/screenshots"
